export const  PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';
export const  PRODUCT_DET_REQUEST = 'PRODUCT_DET_REQUEST';
export const PRODUCT_DET_SUCCESS = 'PRODUCT_DET_SUCCESS';
export const PRODUCT_DET_FAIL = 'PRODUCT_DET_FAIL';